export type Language = 'en' | 'es';
export type TranslationDictionary = any;

const en = {
  nav: { worlds:'Worlds', realWork:'Real Work', packages:'Packages', faq:'FAQ', myParty:'My Party', kernivaOps:'Kerniva Ops', planParty:'Plan a Party' },
  hero: { badge:'Children’s events across London, Watford & Hertfordshire', titleLine1:'Build a party that', titleHighlight:'feels like them', subtitle:'Entertainment, balloons, face painting, inflatables and practical event planning in one place.', planPartyBtn:'Plan your party', exploreWorldsBtn:'Explore the worlds' },
  worlds: {
    sectionTitle:'Choose the atmosphere', sectionSubtitle:'Each world changes the feel of the experience while the booking data stays connected to Kerniva.',
    parties:{name:'Party Entertainment',tag:'Games · Music · Hosts',desc:'High-energy bilingual entertainment built around the age group, venue and guest list.',stat:'Ages 3–10'},
    facePaint:{name:'Face Painting',tag:'Art · Glitter · Gems',desc:'Professional face art using cosmetic products and child-friendly designs.',stat:'Artist-led'},
    balloons:{name:'Balloon Styling',tag:'Arches · Garlands · Sculptures',desc:'Organic balloon installations and individual balloon creations for guests.',stat:'Bespoke'},
    inflatables:{name:'Inflatables & Play',tag:'Castles · Soft Play',desc:'Active play zones selected to suit the venue, age range and available space.',stat:'Indoor / Outdoor'},
    babyEvents:{name:'Baby Events',tag:'Milestones · Soft Play',desc:'Calmer styling and activities for first birthdays, baby showers and family celebrations.',stat:'Family-led'},
    gallery:{name:'Real Events',tag:'Portfolio · Proof',desc:'A visual record of installations, entertainment and celebrations delivered by Polylolli.',stat:'Real work'}
  },
  realWork:{kicker:'Real Polylolli Work',title:'What the service actually looks like',subtitle:'Practical examples of styling, entertainment and activities delivered for real families.',item1Title:'Balloon styling built for the venue',item1Desc:'Colour, scale and installation are adapted to the room and event rather than copied from a generic template.',item2Title:'Face art designed around the child',item2Desc:'Professional face painting with cosmetic products, glitter and age-appropriate designs.',item3Title:'Sweet stations that are served fresh',item3Desc:'Optional popcorn, cotton candy and chocolate fountain stations can be added to larger packages.',item4Title:'A gift for every child',item4Desc:'Every guest can leave with a small party gift, with an extra-special present for the celebrant.'},
  packages:{title:'Choose a package',subtitle:'Package data is presented by Polylolli and designed to be owned operationally by Kerniva.',perParty:'per party',duration:'Duration',guests:'Guests',age:'Age',includesTitle:'Includes',selectPackage:'Select package',depositNotice:'Deposits secure the date and are tracked against the booking in Kerniva.'},
  trust:{kicker:'Trust & Practical Answers',title:'Know what happens before you book',subtitle:'Clear answers for parents and organisers before committing to an event.',faq1Q:'How do I secure the date?',faq1A:'Choose a package, submit the event details and pay the required deposit once the quote is accepted.',faq2Q:'Can I change the guest count later?',faq2A:'Yes. Low-risk preferences such as estimated guest count can be updated through the customer portal.',faq3Q:'Can I change the date or start time?',faq3A:'Confirmed commercial details require a change request so the team can check availability before approving it.',faq4Q:'Which areas do you cover?',faq4A:'Brixton, Greater London, Watford and Hertfordshire, with travel assessed for each booking.',faq5Q:'What ages are the parties for?',faq5A:'Packages are mainly designed for children from roughly ages 2 to 11, depending on the activities selected.',faq6Q:'What if the weather changes?',faq6A:'For outdoor bookings, the team will discuss venue and activity alternatives where possible.'},
  cta:{title:'Ready to build the event?',subtitle:'Start with the date, venue, age range and number of children. We can shape the rest around those details.',button:'Build my party',whatsappNote:'Prefer WhatsApp? Message Polylolli directly on 07938 601802.'},
  wizard:{title:'Build Your Party',step1:'Celebration & Package',step2:'Child & Guests',step4:'Venue & Date',step5:'Contact & Review',celebrationType:'Celebration type',types:{birthday:'Children’s Birthday',babyFirst:'1st Birthday / Milestone',schoolSeason:'School / Seasonal Celebration',family:'Family Gathering'},packageLabel:'Package',childNamePlaceholder:'Child’s first name',childAgeLabel:'Child age',guestsLabel:'Estimated children',themeLabel:'Theme',themePlaceholder:'Princess, superheroes, pastel, football…',venueNamePlaceholder:'Venue name or home',venueAddressPlaceholder:'Address & postcode',dateLabel:'Event date',timeLabel:'Start time',parentNameLabel:'Parent / organiser name',emailLabel:'Email',phoneLabel:'Phone',notesLabel:'Notes, allergies & requirements',notesPlaceholder:'Tell us anything important for the event.',submitBtn:'Send booking request',submittingBtn:'Sending to Kerniva…',successTitle:'Request received',successDesc:'Your enquiry has been safely recorded and a booking reference has been created.',bookingRefLabel:'Booking reference',openPortalBtn:'Open customer portal'},
  portal:{title:'My Party',subtitle:'Customer Booking Portal',refInputPlaceholder:'Booking reference e.g. PLY-26-8K2F',searchBtn:'Search',demoLoadBtn:'Load demo',statusLabel:'Status',packageLabel:'Package',dateLabel:'Date',timeLabel:'Time',depositPaid:'Deposit paid',balanceDue:'Balance due',totalAmount:'Total',quoteReviewTitle:'Quote',quoteReviewDesc:'Review and accept the current Kerniva quote before paying the deposit.',acceptQuoteBtn:'Accept quote',quoteAcceptedBadge:'Quote accepted',preferencesTab:'Preferences',changeRequestTab:'Request a change',preferencesDesc:'Update low-risk event preferences without changing confirmed commercial terms.',allergiesLabel:'Allergies',musicLabel:'Music',themeLabel:'Theme',parkingLabel:'Venue / parking notes',notesLabel:'General notes',savePreferencesBtn:'Save preferences',savingBtn:'Saving…',savedAlert:'Preferences saved in Kerniva.',restrictedNotice:'Date, time, package and pricing changes require business approval.',fieldToChange:'Field to change',newRequestedValue:'Requested value',reasonLabel:'Reason',requestChangeBtn:'Request change',submitChangeBtn:'Submit request',existingRequestsTitle:'Existing requests',statusPending:'Pending',statusApproved:'Approved',statusRejected:'Rejected',statusMap:{CONFIRMED:'Confirmed',ENQUIRY_RECEIVED:'Enquiry received',QUOTE_SENT:'Quote sent',QUOTE_ACCEPTED:'Quote accepted',DEPOSIT_PENDING:'Deposit pending',COMPLETED:'Completed',CANCELLED:'Cancelled'}},
  kernivaDrawer:{title:'Kerniva Operations',badge:'SOURCE OF TRUTH',subtitle:'Operational state for the Polylolli tenant',approveBtn:'Approve',rejectBtn:'Reject'}
};

const es: TranslationDictionary = {
  ...en,
  nav:{worlds:'Mundos',realWork:'Trabajo Real',packages:'Paquetes',faq:'Preguntas',myParty:'Mi Fiesta',kernivaOps:'Kerniva Ops',planParty:'Planear Fiesta'},
  hero:{badge:'Eventos infantiles en Londres, Watford y Hertfordshire',titleLine1:'Crea una fiesta que',titleHighlight:'se sienta suya',subtitle:'Animación, globos, pintacaras, hinchables y planificación práctica del evento en un solo lugar.',planPartyBtn:'Planear mi fiesta',exploreWorldsBtn:'Explorar mundos'},
  worlds:{...en.worlds,sectionTitle:'Elige la atmósfera',sectionSubtitle:'Cada mundo cambia la experiencia visual mientras los datos de reserva permanecen conectados a Kerniva.'},
  packages:{...en.packages,title:'Elige un paquete',subtitle:'Polylolli presenta la experiencia; Kerniva mantiene el estado operativo.',perParty:'por fiesta',duration:'Duración',guests:'Invitados',age:'Edad',includesTitle:'Incluye',selectPackage:'Elegir paquete',depositNotice:'El depósito reserva la fecha y queda registrado contra la reserva en Kerniva.'},
  trust:{...en.trust,kicker:'Confianza y Respuestas',title:'Sabe qué ocurrirá antes de reservar',subtitle:'Respuestas claras para familias y organizadores antes de confirmar.'},
  cta:{title:'¿Listo para crear el evento?',subtitle:'Empieza por fecha, lugar, edades y número de niños. Construimos el resto alrededor de esos datos.',button:'Crear mi fiesta',whatsappNote:'¿Prefieres WhatsApp? Escríbenos directamente al 07938 601802.'},
  wizard:{...en.wizard,title:'Crea Tu Fiesta',celebrationType:'Tipo de celebración',packageLabel:'Paquete',childNamePlaceholder:'Nombre del niño/a',childAgeLabel:'Edad',guestsLabel:'Niños aproximados',themeLabel:'Tema',themePlaceholder:'Princesas, superhéroes, pastel, fútbol…',dateLabel:'Fecha',timeLabel:'Hora de inicio',parentNameLabel:'Nombre del padre/madre u organizador',emailLabel:'Email',phoneLabel:'Teléfono',notesLabel:'Notas, alergias y necesidades',notesPlaceholder:'Cuéntanos cualquier detalle importante.',submitBtn:'Enviar solicitud',submittingBtn:'Enviando a Kerniva…',successTitle:'Solicitud recibida',successDesc:'La consulta quedó registrada de forma segura y se creó una referencia.',bookingRefLabel:'Referencia',openPortalBtn:'Abrir portal'},
  portal:{...en.portal,title:'Mi Fiesta',subtitle:'Portal de Reserva',searchBtn:'Buscar',demoLoadBtn:'Cargar demo',packageLabel:'Paquete',dateLabel:'Fecha',timeLabel:'Hora',depositPaid:'Depósito pagado',balanceDue:'Saldo pendiente',totalAmount:'Total',preferencesTab:'Preferencias',changeRequestTab:'Solicitar cambio',savePreferencesBtn:'Guardar preferencias',savingBtn:'Guardando…',savedAlert:'Preferencias guardadas en Kerniva.',requestChangeBtn:'Solicitar cambio',submitChangeBtn:'Enviar solicitud'},
  kernivaDrawer:{title:'Operaciones Kerniva',badge:'FUENTE DE VERDAD',subtitle:'Estado operativo del tenant Polylolli',approveBtn:'Aprobar',rejectBtn:'Rechazar'}
};

export const translations: Record<Language, TranslationDictionary> = { en, es };
